sylius_resource:
    resources:
        brille24.channel_special_pricing:
            classes:
                model: Brille24\SyliusSpecialPricePlugin\Entity\ChannelSpecialPricing
                interface: Brille24\SyliusSpecialPricePlugin\Entity\ChannelSpecialPricingInterface
